---
# tasks file for nginx_custom
- name: Подмена веб-страницы
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html/index.html
  register: nginx_page

- name: Перезагрузить nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  when: nginx_page.changed
